config/routes.rb
Rails.application.routes.draw do

  get 'dreamsigns' => 'dreamsigns#index'
  resources :dreams

  root 'dreams#index'

end

app/models/dream.rb
class Dream < ActiveRecord::Base
  has_many :dream_dreamsigns, dependent: :destroy
  has_many :dreamsigns, through: :dream_dreamsigns

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/dream_dreamsign.rb
class DreamDreamsign < ActiveRecord::Base
  belongs_to :dream
  belongs_to :dreamsign
end

app/models/dreamsign.rb
class Dreamsign < ActiveRecord::Base
  has_many :dream_dreamsigns, dependent: :destroy
  has_many :dreams, through: :dream_dreamsigns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  def index
    @dreams = Dream.order("created_at DESC")
    @dream = Dream.new
    @form_hidden = true
  end

  def show
    @dream = Dream.find(params[:id])
  end

  def create
    @dream = Dream.new(dream_params)

    if @dream.save
      flash[:success] = 'Dream was successfully added'
      redirect_to @dream
    else
      @dreams = Dream.all
      render 'index', locals: {form_hidden: false}
    end
  end

  private
    def dream_params
      params.require(:dream).permit(:name, :description, :date, :lucid, dreamsign_ids: [] )
    end
end

app/controllers/dreamsigns_controller.rb
class DreamsignsController < ApplicationController
  def index
    @dreamsigns = Dreamsign.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/dreamsigns_helper.rb
module DreamsignsHelper
end

app/views/dreams/_dream.html.erb
<article>
  <h3><%= link_to dream.name, dream %></h3>
  <p><%= dream.description %></p>
</article>

app/views/dreams/_form.html.erb
<div class="dream-form">  
  <h2>Add new dream</h2>
  <%= form_for(@dream) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="form-group">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </div>

    <div class="form-group">
      <%= f.text_area :description, rows: 7, class: 'form-control', placeholder: 'Description' %>
    </div>

    <div class="form-group">
      <%= f.check_box :lucid %>
      <%= f.label :lucid, 'Lucid?', class: 'checkbox-inline' %>
    </div>

    <div class='form-group'>
      <label>Dreamsigns:</label>
      <%= f.collection_check_boxes(:dreamsign_ids, Dreamsign.all, :id, :name) do |b| %>
        <br>
        <%= b.check_box %>
        <%= b.label(class: 'checkbox-inline') %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.datetime_select :date, class: 'form-control', placeholder: 'Date' %>
    </div>
    <div class='form-group'>
      <%= f.submit class: 'btn btn-primary', id: 'create-dream' %>
    </div>
  <% end %>
</div>

app/views/dreams/index.html.erb
<h1>Dreams</h1>
<button class="btn btn-primary" id="add-dream">Add dream</button>

<!-- pass variable to JS -->
<%= javascript_tag do %>
  window.form_hidden = '<%= @form_hidden %>';
<% end %>

<%= render 'form' %>

<%= render @dreams %>

app/views/dreams/show.html.erb
<h3>Name</h3>
<p><%= @dream.name %></p>
<h3>Date</h3>
<p><%= @dream.date %></p>
<h3>Description</h3>
<p><%= @dream.description %></p>
<h3>Lucid?</h3>
<p><%= @dream.lucid ? "Yes" : "No" %></p>
<h3>Dream Signs in this dream:</h3>
<ul>
  <% @dream.dreamsigns.each do |dreamsign| %>
    <li><%= dreamsign.name %></li>
  <% end %>
</ul>
<%= link_to "<- back to dreams", dreams_path %>

app/views/dreamsigns/_dreamsign.html.erb
<article>
  <h3><%= dreamsign.name %></h3>
  <p><%= dreamsign.description %></p>
</article>

app/views/dreamsigns/index.html.erb
<h1>Dreamsigns</h1>
<%= render @dreamsigns %>

app/views/dreamsigns/show.html.erb
<h1>Dreamsigns#show</h1>
<p>Find me in app/views/dreamsigns/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-md-4 col-mdoffset-2">

    </div>
    <div class="col-md-4">
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <h1 id="logo">Dream Journal</h1>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Dreams", dreams_path %></li>
        <li><%= link_to "Dreamsigns", dreamsigns_path %></li>
        <li><a href="#">Account</a></li>
      </ul > 
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <title>DreamApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class='flash-messages'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-2">
          <section class="main-content">

            <%= yield %>

          </section>
        </div>

        <div class="col-md-2">
          <aside class="search-sidebar">
            <h2>Search dreams</h2>
            <p>Browse dreams here</p>
          </aside>
        </div>
      </div>
    </div> <!-- container -->

    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @dream.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@dream.errors.count, "error") %>.
    </div>
    <ul>
    <% @dream.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>